### ISSUE TITLE
Module `recompose` does not exist in the Haste module map

### ISSUE THREAD

**Issue by akashdeepsharma1991** [passpier/react-native-smooth-pull-to-refresh#2]
Desktop/xxx/xxxx/node_modules/react-native-smooth-pull-to-refresh/dist/src/PullToRefreshView.ios.js`: Module `recompose` does not exist in the Haste module map
any one know how to fix this issue

**Comment by kldkv** [comment]
`npm i -S recompose styled-components@3` 
its working for me

--
`react-native start --reset-cache`
